In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
data=pd.read_csv('housing.csv')

In [7]:
data.head()

      RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0
2  7.185   4.03     17.8  728700.0
3  6.998   2.94     18.7  701400.0
4  7.147   5.33     18.7  760200.0

In [8]:
data.tail()

        RM  LSTAT  PTRATIO      MEDV
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

In [9]:
data.shape

(489, 4)

In [10]:
data.info

<bound method DataFrame.info of         RM  LSTAT  PTRATIO      MEDV
0    6.575   4.98     15.3  504000.0
1    6.421   9.14     17.8  453600.0
2    7.185   4.03     17.8  728700.0
3    6.998   2.94     18.7  701400.0
4    7.147   5.33     18.7  760200.0
..     ...    ...      ...       ...
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

[489 rows x 4 columns]>

In [11]:
data.dtypes

RM         float64
LSTAT      float64
PTRATIO    float64
MEDV       float64
dtype: object

In [12]:
data.isnull()

        RM  LSTAT  PTRATIO   MEDV
0    False  False    False  False
1    False  False    False  False
2    False  False    False  False
3    False  False    False  False
4    False  False    False  False
..     ...    ...      ...    ...
484  False  False    False  False
485  False  False    False  False
486  False  False    False  False
487  False  False    False  False
488  False  False    False  False

[489 rows x 4 columns]

In [13]:
data.isnull().sum()

RM         0
LSTAT      0
PTRATIO    0
MEDV       0
dtype: int64

In [18]:
X=data.drop(columns='MEDV')
y=data['MEDV']

In [19]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3, random_state=100)

In [20]:
lin_reg=LinearRegression()
lin_reg.fit(X_train, y_train)

LinearRegression()

In [21]:
lin_reg.coef_

array([ 93284.16172636, -10463.82070679, -19733.22721828])

In [22]:
lin_reg.intercept_

np.float64(373759.8345017253)

In [30]:
y_pred=lin_reg.predict(X_test)

In [31]:
pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})

       Actual      Predicted
244  621600.0  608895.820668
352  352800.0  363286.300043
265  672000.0  634642.494226
97   812700.0  727218.960367
310  485100.0  509881.947935
..        ...            ...
126  329700.0  235215.441935
302  453600.0  512522.827479
419  201600.0  388985.649849
464  497700.0  523826.764075
459  350700.0  384538.978523

[147 rows x 2 columns]

In [32]:
r2_score(y_test, y_pred)

0.7299486664739843